### ISSUE TITLE
Code Review for Team (C) from Team (E) 

### ISSUE THREAD

**Issue by kehuang11** [LogsC/EEP153-Project3-Spring2023#1]
I was able to successfully run the code and replicate the results.  

One suggestion I have is to update the README to include some information about your topic, project, etc. This will help improve clarity of your goals.

Other than that, perhaps remove the unused commented code to make the code cleaner. Overall, good job!!!

**Comment by LogsC** [comment]
Thank you for letting us know! We will work on your suggestions!
