### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Jaydenm5** [LogsC/EEP153-Project3-Spring2023#2]
I was able to get all of the code to run and work smoothly without any errors. One recommendation I have for your team is to clean up the visualizations a bit, by adding titles and labeling the axis, this will provide the reader/audience with more clarity as to what you arer trying to show via the graphics.  Other than that, great job! I guess if you wanted to, you could make the code more elegant by getting rid of # word chunks.

**Comment by LogsC** [comment]
Thank you for the suggestions, we will look into it!
